// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZhQCV86Cw3jVuVyojg2jsNfoCeUTmEWA',
    appId: '1:84715631652:web:96faed113aa4e51fdb94b1',
    messagingSenderId: '84715631652',
    projectId: 'ezzem-a21ea',
    authDomain: 'ezzem-a21ea.firebaseapp.com',
    storageBucket: 'ezzem-a21ea.appspot.com',
    measurementId: 'G-VKDRGFW0N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmt8VU2rBGHYS8YUaOZzNXU4F0lEaIbkA',
    appId: '1:84715631652:android:ab43afb40d61669ddb94b1',
    messagingSenderId: '84715631652',
    projectId: 'ezzem-a21ea',
    storageBucket: 'ezzem-a21ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAISVnG4n-xKV7ULgix_wv0nt6tmVoknak',
    appId: '1:84715631652:ios:1891f677a10882b7db94b1',
    messagingSenderId: '84715631652',
    projectId: 'ezzem-a21ea',
    storageBucket: 'ezzem-a21ea.appspot.com',
    iosClientId: '84715631652-sfamp9rjpaldplgkoh8pfrn9oevm01k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezzem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAISVnG4n-xKV7ULgix_wv0nt6tmVoknak',
    appId: '1:84715631652:ios:1891f677a10882b7db94b1',
    messagingSenderId: '84715631652',
    projectId: 'ezzem-a21ea',
    storageBucket: 'ezzem-a21ea.appspot.com',
    iosClientId: '84715631652-sfamp9rjpaldplgkoh8pfrn9oevm01k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezzem',
  );

}